### ISSUE TITLE
Will it also prevent counting outside ActiveAdmin?

### ISSUE THREAD

**Issue by pomartel** [pawurb/dont_you_count#1]
Reading the source code, I have a doubt that this does not just apply for ActiveAdmin but for the model through the whole application. For example, I don't want kaminari counting in ActiveAdmin but I do want it in other parts of the app. Will it work? Is it scoped to only prevent counting in ActiveAdmin?

**Comment by pawurb** [comment]
It is not scoped. Gem is just a wrapper for hack I used for in application. Yesterday a smarter fix for this issue was merged into AA master. Check out: https://github.com/activeadmin/activeadmin/commit/3f9efd1c57ca78477ea9eb8268812bf5a038565d

**Comment by pomartel** [comment]
Great! Thanks for letting me know.
